"""Document Orchestrator — parses any KB document into typed blocks.

Runs at ingest (and on every edit per the locked decision: full re-parse
on every edit/sync — drift between source doc and structured chunks is
worse than the LLM cost). Each typed block becomes a ``KBChunk`` row
with ``kind`` set, ``extracted_metadata`` populated per the per-kind
schema, and an embedding generated by the existing Voyage embedder.

The orchestrator is *additive* on top of the existing chunker: if the
LLM call fails or produces no usable blocks, we fall back to token-based
chunks tagged ``kind='context'`` so retrieval still has something to
work with. This keeps KB ingest robust to LLM hiccups.

Side effects beyond writing chunks:

* Populates ``kb_integration_gaps`` for procedures that reference
  integrations the tenant has not connected.
* On admin connect/disconnect of an integration, ``reevaluate_gaps``
  refreshes the gap table without re-running the orchestrator.
"""
from __future__ import annotations

import hashlib
import json
import logging
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Sequence

import anthropic
from sqlalchemy import select, text as sql_text
from sqlalchemy.ext.asyncio import AsyncSession

from backend.app.config import get_settings
from backend.app.models import (
    Integration,
    KBChunk,
    KBDocument,
    KBIntegrationGap,
)
from backend.app.services import metrics as _metrics
from backend.app.services.kb.chunker import approx_token_count, chunk_text
from backend.app.services.kb.embedder import VoyageEmbedder, VoyageEmbedderError
from backend.app.services.kb.orchestrator_prompts import (
    format_orchestrator_system,
    format_orchestrator_user,
)
from backend.app.services.kb.vector_store import (
    ChunkRecord,
    VectorStore,
    get_vector_store,
)
from backend.app.services.llm_client import get_async_anthropic
from backend.app.services.triage_service import _strip_json_fences
from backend.app.services.llm_client import model_for_tier

logger = logging.getLogger(__name__)


_ORCHESTRATOR_MODEL = model_for_tier("haiku")
_ORCHESTRATOR_MAX_TOKENS = 8192
# Documents longer than this fall through to plain chunking — one
# orchestrator call can only see so much before quality + latency
# degrade. Lowered from 50K → 40K (2026-06 audit): a failed parse on a
# near-50K doc burns ~12.5K input tokens for nothing, and parse quality
# on borderline docs was the least reliable. ~40K chars ~ 10K tokens.
# Watch KB_ORCHESTRATOR_PARSE_OUTCOMES before moving this again —
# multi-pass parsing is the real fix if large docs become common.
_ORCHESTRATOR_MAX_CHARS = 40_000


def _size_bucket(chars: int) -> str:
    if chars <= 10_000:
        return "<10k"
    if chars <= 25_000:
        return "10-25k"
    if chars <= _ORCHESTRATOR_MAX_CHARS:
        return "25-40k"
    return ">40k"

# Confidence below this lands as kind='context' regardless of the
# model's pick (per the locked decision). The original confidence is
# preserved so the admin queue can show it.
_LOW_CONFIDENCE_THRESHOLD = 0.5

# Valid block kinds — must match the kb_chunks CHECK constraint.
_VALID_KINDS = frozenset(
    {
        "procedure",
        "policy",
        "escalation_path",
        "template",
        "context",
        "faq",
        "glossary",
        "contact_directory",
    }
)


def _hash_content(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


@dataclass
class _OrchBlock:
    """One block emitted by the orchestrator, normalized."""

    kind: str
    title: str
    content: str
    extracted_metadata: Dict[str, Any]
    confidence: float
    source_span_start: Optional[int]
    source_span_end: Optional[int]


class DocumentOrchestrator:
    """Segments KB documents into typed blocks via Claude Haiku."""

    def __init__(
        self,
        client: Optional[anthropic.AsyncAnthropic] = None,
    ) -> None:
        self._client = client or get_async_anthropic()

    async def parse(
        self,
        *,
        tenant_name: str,
        doc: KBDocument,
    ) -> List[_OrchBlock]:
        """Call the orchestrator on one document and return typed blocks.

        On any failure (LLM error, malformed JSON, oversized doc), returns
        ``[]`` and lets the caller fall back to plain chunking.
        """
        if not doc.content or not doc.content.strip():
            return []
        bucket = _size_bucket(len(doc.content))
        if len(doc.content) > _ORCHESTRATOR_MAX_CHARS:
            logger.info(
                "Doc %s exceeds orchestrator max chars (%d > %d); will fall "
                "back to plain chunking",
                doc.id, len(doc.content), _ORCHESTRATOR_MAX_CHARS,
            )
            _metrics.KB_ORCHESTRATOR_PARSE_OUTCOMES.labels(
                outcome="oversized", size_bucket=bucket
            ).inc()
            return []

        system_prompt = format_orchestrator_system(
            tenant_name=tenant_name or "the tenant",
        )
        user_content = format_orchestrator_user(
            title=doc.title or "(untitled)",
            source_description=doc.source_type or "uploaded",
            char_count=len(doc.content),
            content=doc.content,
        )

        try:
            response = await self._client.messages.create(
                model=_ORCHESTRATOR_MODEL,
                max_tokens=_ORCHESTRATOR_MAX_TOKENS,
                # The system prompt is constant per tenant — cache it so
                # backfill of N documents only pays for the prompt
                # tokens once per tenant within the 5-min cache window.
                system=[
                    {
                        "type": "text",
                        "text": system_prompt,
                        "cache_control": {"type": "ephemeral"},
                    }
                ],
                messages=[{"role": "user", "content": user_content}],
            )
        except anthropic.APIError as exc:
            logger.warning(
                "Orchestrator API call failed for doc %s: %s", doc.id, exc,
            )
            _metrics.KB_ORCHESTRATOR_PARSE_OUTCOMES.labels(
                outcome="api_error", size_bucket=bucket
            ).inc()
            return []

        try:
            raw = response.content[0].text
            data = json.loads(_strip_json_fences(raw))
        except (json.JSONDecodeError, IndexError, KeyError, AttributeError):
            logger.warning(
                "Orchestrator returned unparseable JSON for doc %s",
                doc.id, exc_info=True,
            )
            _metrics.KB_ORCHESTRATOR_PARSE_OUTCOMES.labels(
                outcome="bad_json", size_bucket=bucket
            ).inc()
            return []

        _metrics.KB_ORCHESTRATOR_PARSE_OUTCOMES.labels(
            outcome="ok", size_bucket=bucket
        ).inc()
        return _normalize_blocks(data, total_chars=len(doc.content))


def _normalize_blocks(data: Any, *, total_chars: int) -> List[_OrchBlock]:
    """Coerce the LLM's free-shape JSON into validated ``_OrchBlock`` rows."""
    if not isinstance(data, dict):
        return []
    raw_blocks = data.get("blocks") or []
    if not isinstance(raw_blocks, list):
        return []

    out: List[_OrchBlock] = []
    for entry in raw_blocks:
        if not isinstance(entry, dict):
            continue
        kind = str(entry.get("kind") or "context").strip()
        if kind not in _VALID_KINDS:
            kind = "context"

        confidence = entry.get("confidence")
        try:
            confidence_f = float(confidence) if confidence is not None else 0.5
        except (TypeError, ValueError):
            confidence_f = 0.5
        confidence_f = max(0.0, min(1.0, confidence_f))

        # Locked decision: low-confidence spans land as 'context' and
        # get surfaced to admin review. We preserve the original
        # confidence so the admin queue can show why.
        if confidence_f < _LOW_CONFIDENCE_THRESHOLD:
            kind = "context"

        content = str(entry.get("content") or "").strip()
        if not content:
            continue
        title = str(entry.get("title") or "")[:200]
        meta = entry.get("extracted_metadata")
        if not isinstance(meta, dict):
            meta = {}

        span = entry.get("source_span") or {}
        start = _coerce_int_in_range(span.get("start_char"), 0, total_chars)
        end = _coerce_int_in_range(span.get("end_char"), 0, total_chars)
        if start is not None and end is not None and end < start:
            start, end = end, start

        out.append(
            _OrchBlock(
                kind=kind,
                title=title,
                content=content,
                extracted_metadata=meta,
                confidence=confidence_f,
                source_span_start=start,
                source_span_end=end,
            )
        )
    return out


def _coerce_int_in_range(
    value: Any, lo: int, hi: int,
) -> Optional[int]:
    try:
        ivalue = int(value)
    except (TypeError, ValueError):
        return None
    return max(lo, min(hi, ivalue))


# ──────────────────────────────────────────────────────────
# Top-level ingest entry — replaces ``ingest_document`` for tenants
# that have the orchestrator enabled.
# ──────────────────────────────────────────────────────────


async def ingest_document_orchestrated(
    db: AsyncSession,
    doc: KBDocument,
    *,
    tenant_name: str,
    embedder: Optional[VoyageEmbedder] = None,
    store: Optional[VectorStore] = None,
    orchestrator: Optional[DocumentOrchestrator] = None,
    force: bool = False,
) -> int:
    """Parse, chunk, embed, and store one document.

    1. Call the orchestrator. If it yields blocks, each block becomes a
       typed KBChunk row.
    2. If the orchestrator yielded nothing (too big, LLM failed, parse
       failed), fall back to the existing token-based chunker and tag
       every chunk ``kind='context'`` so it stays retrievable.
    3. Embed every chunk and upsert into the vector store.
    4. For ``kind='procedure'`` blocks whose ``required_integrations``
       reference an unconnected provider, write a row into
       ``kb_integration_gaps`` so the admin alignment report can
       surface them.

    Returns the number of chunks written. No-op when the doc's
    content_hash matches and ``force`` is False.
    """
    if not doc.content or not doc.content.strip():
        logger.info("Skipping orchestrator ingest for doc %s — empty", doc.id)
        return 0

    new_hash = _hash_content(doc.content)
    if not force and doc.content_hash == new_hash and doc.embedded_at is not None:
        return 0

    settings = get_settings()
    embedder = embedder or VoyageEmbedder()
    store = store or get_vector_store()
    orchestrator = orchestrator or DocumentOrchestrator()

    blocks = await orchestrator.parse(tenant_name=tenant_name, doc=doc)

    # Drop prior chunks + gaps for this doc before writing new ones.
    await store.delete_doc(db, doc.tenant_id, doc.id)
    await db.execute(
        KBChunk.__table__.delete().where(KBChunk.doc_id == doc.id)
    )
    await db.execute(
        KBIntegrationGap.__table__.delete().where(
            KBIntegrationGap.doc_id == doc.id
        )
    )

    if not blocks:
        # Fall back to plain token-chunking; everything tagged context.
        pieces = chunk_text(
            doc.content,
            target_tokens=settings.KB_CHUNK_TOKENS,
            overlap_tokens=settings.KB_CHUNK_OVERLAP_TOKENS,
        )
        blocks = [
            _OrchBlock(
                kind="context",
                title=doc.title or "",
                content=piece,
                extracted_metadata={},
                confidence=0.0,
                source_span_start=None,
                source_span_end=None,
            )
            for piece in pieces
        ]
        if not blocks:
            return 0

    try:
        embeddings = await embedder.embed(
            [b.content for b in blocks], input_type="document",
        )
    except VoyageEmbedderError:
        logger.exception("Voyage embed failed for doc %s", doc.id)
        raise

    # Pull connected integrations once so the gap check is cheap.
    connected_providers = await _connected_provider_set(db, doc.tenant_id)

    records: List[ChunkRecord] = []
    new_gaps: List[KBIntegrationGap] = []
    for idx, (block, vec) in enumerate(zip(blocks, embeddings)):
        chunk_id = uuid.uuid4()
        db.add(
            KBChunk(
                id=chunk_id,
                tenant_id=doc.tenant_id,
                doc_id=doc.id,
                chunk_idx=idx,
                text=block.content,
                token_count=approx_token_count(block.content),
                content_hash=_hash_content(block.content),
                kind=block.kind,
                extracted_metadata=block.extracted_metadata,
                classification_confidence=block.confidence,
                source_span_start=block.source_span_start,
                source_span_end=block.source_span_end,
            )
        )
        records.append(
            ChunkRecord(
                id=chunk_id,
                tenant_id=doc.tenant_id,
                doc_id=doc.id,
                chunk_idx=idx,
                text=block.content,
                embedding=vec,
                doc_title=doc.title,
                source_url=doc.source_url,
            )
        )
        if block.kind == "procedure":
            new_gaps.extend(
                _gaps_for_procedure(
                    chunk_id=chunk_id,
                    doc=doc,
                    block=block,
                    connected_providers=connected_providers,
                )
            )

    for gap in new_gaps:
        db.add(gap)

    await store.upsert(db, records)
    doc.content_hash = new_hash
    doc.embedded_at = datetime.now(timezone.utc)

    logger.info(
        "Orchestrated doc %s: %d chunks (%s); %d integration gaps",
        doc.id, len(records),
        _kind_summary(blocks),
        len(new_gaps),
    )
    return len(records)


def _kind_summary(blocks: Sequence[_OrchBlock]) -> str:
    counts: Dict[str, int] = {}
    for b in blocks:
        counts[b.kind] = counts.get(b.kind, 0) + 1
    return ", ".join(f"{k}={v}" for k, v in sorted(counts.items()))


async def _connected_provider_set(
    db: AsyncSession, tenant_id: uuid.UUID,
) -> set:
    rows = await db.execute(
        select(Integration.provider).where(Integration.tenant_id == tenant_id)
    )
    return {row[0] for row in rows.all() if row[0]}


def _gaps_for_procedure(
    *,
    chunk_id: uuid.UUID,
    doc: KBDocument,
    block: _OrchBlock,
    connected_providers: set,
) -> List[KBIntegrationGap]:
    """Emit a gap row for every required integration not connected."""
    meta = block.extracted_metadata or {}
    required = meta.get("required_integrations") or []
    if not isinstance(required, list):
        return []
    compliance = str(meta.get("compliance_level") or "should")
    if compliance not in {"must", "should", "may"}:
        compliance = "should"
    gaps: List[KBIntegrationGap] = []
    for entry in required:
        if not isinstance(entry, dict):
            continue
        provider = str(entry.get("provider") or "").strip().lower()
        if not provider or provider in connected_providers:
            continue
        operation = entry.get("operation")
        if operation is not None:
            operation = str(operation)[:64]
        gaps.append(
            KBIntegrationGap(
                tenant_id=doc.tenant_id,
                chunk_id=chunk_id,
                doc_id=doc.id,
                procedure_title=block.title or None,
                required_provider=provider[:32],
                operation=operation,
                compliance_level=compliance,
            )
        )
    return gaps


# ──────────────────────────────────────────────────────────
# Integration-connect re-evaluation
# ──────────────────────────────────────────────────────────
# Per the locked decision: when a tenant connects a new integration,
# any previously-gated procedures become eligible immediately. We
# don't need to re-run the orchestrator — we just clear gap rows for
# the now-connected provider. Newly-disconnected providers re-trigger
# gap rows for any procedure that referenced them.


async def reevaluate_gaps(
    db: AsyncSession,
    tenant_id: uuid.UUID,
) -> Dict[str, int]:
    """Refresh ``kb_integration_gaps`` against the current Integration set.

    Returns ``{"cleared": N, "added": M}`` for logging / audit.
    """
    connected = await _connected_provider_set(db, tenant_id)

    # Clear gaps whose provider is now connected.
    if connected:
        params = {"tenant_id": str(tenant_id)}
        # Build IN clause with named params.
        placeholders = []
        for i, p in enumerate(connected):
            key = f"p_{i}"
            params[key] = p
            placeholders.append(f":{key}")
        cleared_sql = (
            "DELETE FROM kb_integration_gaps "
            "WHERE tenant_id = :tenant_id "
            f"AND required_provider IN ({', '.join(placeholders)}) "
            "RETURNING id"
        )
        result = await db.execute(sql_text(cleared_sql), params)
        cleared = len(result.all())
    else:
        cleared = 0

    # Re-scan procedures for gaps. We walk procedure-kind chunks and
    # add rows for any required_integrations missing from `connected`.
    proc_chunks = await db.execute(
        select(KBChunk).where(
            KBChunk.tenant_id == tenant_id,
            KBChunk.kind == "procedure",
        )
    )
    added = 0
    for chunk in proc_chunks.scalars():
        doc = await db.get(KBDocument, chunk.doc_id)
        if doc is None:
            continue
        block = _OrchBlock(
            kind="procedure",
            title=str(chunk.extracted_metadata.get("title") or "")
            if isinstance(chunk.extracted_metadata, dict)
            else "",
            content=chunk.text,
            extracted_metadata=chunk.extracted_metadata or {},
            confidence=chunk.classification_confidence or 0.0,
            source_span_start=chunk.source_span_start,
            source_span_end=chunk.source_span_end,
        )
        for gap in _gaps_for_procedure(
            chunk_id=chunk.id,
            doc=doc,
            block=block,
            connected_providers=connected,
        ):
            # Skip if a duplicate already exists (uq_kb_integration_gap).
            existing = await db.execute(
                select(KBIntegrationGap.id).where(
                    KBIntegrationGap.chunk_id == gap.chunk_id,
                    KBIntegrationGap.required_provider == gap.required_provider,
                    KBIntegrationGap.operation == gap.operation,
                )
            )
            if existing.first() is None:
                db.add(gap)
                added += 1

    return {"cleared": cleared, "added": added}


__all__ = [
    "DocumentOrchestrator",
    "ingest_document_orchestrated",
    "reevaluate_gaps",
]
