"""initial schema

Revision ID: 550a40162883
Revises:
Create Date: 2026-04-15 13:11:07.364439
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '550a40162883'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ── Fresh-DB bootstrap ──────────────────────────────────────────────────
# This migration was originally autogenerated against a v1 schema that
# already had ``tenants``, ``users`` and ``action_items`` (created by the
# old seed scripts).  On a fresh DB those tables don't exist and the
# add_column / drop_column / alter_column / drop_constraint calls below
# would crash.  ``_bootstrap_v1_prereqs`` creates the minimum pre-migration
# shape — only when the tables are absent — so this migration can serve as
# the true initial migration on a clean DB while remaining idempotent on
# already-bootstrapped instances.


def _bootstrap_v1_prereqs() -> None:
    bind = op.get_bind()
    existing = set(inspect(bind).get_table_names())

    if "tenants" not in existing:
        op.create_table(
            "tenants",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("name", sa.String(), nullable=False),
            sa.Column("slug", sa.String(), nullable=False),
            sa.Column(
                "branding_config",
                postgresql.JSONB(astext_type=sa.Text()),
                server_default=sa.text("'{}'::jsonb"),
                nullable=True,
            ),
            sa.Column(
                "plan",
                sa.String(length=50),
                server_default=sa.text("'enterprise'::character varying"),
                nullable=True,
            ),
            sa.Column(
                "settings",
                postgresql.JSONB(astext_type=sa.Text()),
                server_default=sa.text("'{}'::jsonb"),
                nullable=True,
            ),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("slug"),
        )

    if "users" not in existing:
        op.create_table(
            "users",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("tenant_id", sa.UUID(), nullable=True),
            sa.Column("email", sa.String(), nullable=False),
            sa.Column(
                "role",
                sa.String(length=50),
                server_default=sa.text("'member'::character varying"),
                nullable=True,
            ),
            sa.Column("full_name", sa.String(length=255), nullable=True),
            sa.Column(
                "is_active",
                sa.Boolean(),
                server_default=sa.text("true"),
                nullable=True,
            ),
            sa.Column("department", sa.String(length=100), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint(
                "tenant_id", "email", name="users_tenant_id_email_key"
            ),
        )

    if "action_items" not in existing:
        op.create_table(
            "action_items",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("tenant_id", sa.UUID(), nullable=True),
            sa.Column("title", sa.String(), nullable=False),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("category", sa.String(), nullable=True),
            sa.Column(
                "priority",
                sa.String(length=20),
                server_default=sa.text("'medium'::character varying"),
                nullable=True,
            ),
            sa.Column(
                "status",
                sa.String(length=50),
                server_default=sa.text("'pending'::character varying"),
                nullable=True,
            ),
            sa.Column("due_date", sa.Date(), nullable=True),
            sa.Column("assigned_to", sa.UUID(), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.PrimaryKeyConstraint("id"),
        )


def upgrade() -> None:
    # Bootstrap the three v1 prerequisite tables on fresh DBs.  No-op when
    # they already exist (e.g. on instances seeded by the legacy scripts).
    _bootstrap_v1_prereqs()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('crm_id', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kb_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_external_id', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('qdrant_point_id', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scorecard_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channel_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('crm_id', sa.String(), nullable=True),
    sa.Column('crm_source', sa.String(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment_trend', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('audio_s3_key', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('caller_phone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pii_redacted', sa.Boolean(), nullable=False),
    sa.Column('call_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('analysis_tier', sa.String(), nullable=True),
    sa.Column('transcript_translated', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_language', sa.String(), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_sec', sa.Float(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('criterion_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['scorecard_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_snippets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('snippet_type', sa.String(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transcript_excerpt', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('in_library', sa.Boolean(), nullable=False),
    sa.Column('library_category', sa.String(), nullable=True),
    sa.Column('promoted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('transcript_buffer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coaching_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Drop old schema tables — must drop dependents first, then parents
    # Use raw SQL with CASCADE to handle any remaining FK constraints
    op.execute('DROP TABLE IF EXISTS ai_insights CASCADE')
    op.execute('DROP TABLE IF EXISTS transcript_segments CASCADE')
    op.execute('DROP TABLE IF EXISTS transcripts CASCADE')
    op.execute('DROP INDEX IF EXISTS idx_calls_tenant')
    op.execute('DROP INDEX IF EXISTS idx_calls_type')
    op.execute('DROP TABLE IF EXISTS calls CASCADE')
    # Drop old FK constraints on action_items before adding new columns
    op.execute("ALTER TABLE action_items DROP CONSTRAINT IF EXISTS action_items_call_id_fkey")
    op.execute("ALTER TABLE action_items DROP CONSTRAINT IF EXISTS action_items_insight_id_fkey")
    op.execute("ALTER TABLE action_items DROP CONSTRAINT IF EXISTS action_items_tenant_id_fkey")
    op.execute("ALTER TABLE action_items DROP COLUMN IF EXISTS call_id")
    op.execute("ALTER TABLE action_items DROP COLUMN IF EXISTS insight_id")
    op.execute("ALTER TABLE action_items DROP COLUMN IF EXISTS updated_at")
    op.add_column('action_items', sa.Column('interaction_id', sa.UUID(), nullable=True))
    op.add_column('action_items', sa.Column('calendar_event_id', sa.String(), nullable=True))
    op.add_column('action_items', sa.Column('email_draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('action_items', sa.Column('automation_status', sa.String(), nullable=False))
    op.alter_column('action_items', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('action_items', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('action_items', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('action_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # FK constraints already dropped via raw SQL above
    op.create_foreign_key(None, 'action_items', 'interactions', ['interaction_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'action_items', 'tenants', ['tenant_id'], ['id'])
    # call_id, updated_at, insight_id already dropped via raw SQL above
    op.add_column('tenants', sa.Column('transcription_engine', sa.String(), nullable=False, server_default='deepgram'))
    op.add_column('tenants', sa.Column('automation_level', sa.String(), nullable=False, server_default='approval'))
    op.add_column('tenants', sa.Column('pii_redaction_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('tenants', sa.Column('pii_redaction_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.add_column('tenants', sa.Column('audio_storage_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('tenants', sa.Column('enrichment_pdl_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('tenants', sa.Column('enrichment_apollo_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('tenants', sa.Column('keyterm_boost_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('tenants', sa.Column('default_language', sa.String(), nullable=False, server_default='en'))
    op.add_column('tenants', sa.Column('translation_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('tenants', sa.Column('features_enabled', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.alter_column('tenants', 'branding_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'settings')
    op.drop_column('tenants', 'plan')
    op.add_column('users', sa.Column('clerk_user_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'member'::character varying"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_tenant_id_email_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['clerk_user_id'])
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_tenant_id_email_key'), 'users', ['tenant_id', 'email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'member'::character varying"))
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('users', 'name')
    op.drop_column('users', 'clerk_user_id')
    op.add_column('tenants', sa.Column('plan', sa.VARCHAR(length=50), server_default=sa.text("'enterprise'::character varying"), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'branding_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('tenants', 'features_enabled')
    op.drop_column('tenants', 'translation_enabled')
    op.drop_column('tenants', 'default_language')
    op.drop_column('tenants', 'keyterm_boost_list')
    op.drop_column('tenants', 'enrichment_apollo_enabled')
    op.drop_column('tenants', 'enrichment_pdl_enabled')
    op.drop_column('tenants', 'audio_storage_enabled')
    op.drop_column('tenants', 'pii_redaction_config')
    op.drop_column('tenants', 'pii_redaction_enabled')
    op.drop_column('tenants', 'automation_level')
    op.drop_column('tenants', 'transcription_engine')
    op.add_column('action_items', sa.Column('insight_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('action_items', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('action_items', sa.Column('call_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'action_items', type_='foreignkey')
    op.drop_constraint(None, 'action_items', type_='foreignkey')
    op.create_foreign_key(op.f('action_items_call_id_fkey'), 'action_items', 'calls', ['call_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('action_items_insight_id_fkey'), 'action_items', 'ai_insights', ['insight_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('action_items_tenant_id_fkey'), 'action_items', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('action_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_items', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('action_items', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('action_items', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('action_items', 'automation_status')
    op.drop_column('action_items', 'email_draft')
    op.drop_column('action_items', 'calendar_event_id')
    op.drop_column('action_items', 'interaction_id')
    op.create_table('ai_insights',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('call_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), server_default=sa.text("'claude-sonnet-4-6'::character varying"), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sentiment_overall', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('key_moments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('coaching', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('ai_insights_call_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('ai_insights_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_insights_pkey'))
    )
    op.create_table('transcript_segments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transcript_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('speaker_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('speaker_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('start_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.97'), autoincrement=False, nullable=True),
    sa.Column('sentiment', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('seq_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], name=op.f('transcript_segments_transcript_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transcript_segments_pkey'))
    )
    op.create_index(op.f('idx_segs_transcript'), 'transcript_segments', ['transcript_id', 'seq_order'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('call_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=True),
    sa.Column('full_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.97'), autoincrement=False, nullable=True),
    sa.Column('engine', sa.VARCHAR(length=50), server_default=sa.text("'whisper'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('transcripts_call_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('transcripts_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transcripts_pkey'))
    )
    op.create_table('calls',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('call_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('duration_secs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('audio_format', sa.VARCHAR(length=20), server_default=sa.text("'mp3'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'complete'::character varying"), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('calls_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('calls_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('calls_pkey'))
    )
    op.create_index(op.f('idx_calls_type'), 'calls', ['tenant_id', 'call_type'], unique=False)
    op.create_index(op.f('idx_calls_tenant'), 'calls', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_table('live_sessions')
    op.drop_table('interaction_snippets')
    op.drop_table('interaction_scores')
    op.drop_table('interaction_comments')
    op.drop_table('interactions')
    op.drop_table('integrations')
    op.drop_table('contacts')
    op.drop_table('webhooks')
    op.drop_table('tenant_insights')
    op.drop_table('scorecard_templates')
    op.drop_table('kb_documents')
    op.drop_table('companies')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
